// Per-client department catalogs for invoicing.
//
// WHY THIS EXISTS
// Rocio asked (2026-06-17): "For FabFitFun specifically, invoices must be
// generated by department... each department needs to have its own invoice."
//
// The invoicing engine already does that — previewInvoicesForPeriod groups by
// (client, department, branch) and upsertInvoicesForPeriod writes one invoice
// per group. The part that does not work is the DATA feeding it:
//
//   * The department picker offers a generic six-item list — Warehouse,
//     Inventory, Receiving, Shipping, Logistics, Hospitality — which is not what
//     FabFitFun bills under. Their own invoice workbook uses coded departments:
//     502 Warehouse Operations, 503 Inventory Control, 509 QA Production,
//     510 FC Facility Maintenance, 511 FC Engineering. One tab per code.
//   * Measured in production 2026-09-10: 63 of 67 active FabFitFun assignments
//     have department "Unassigned". Generating invoices today yields ONE lump
//     invoice, not the six the workbook shows — and nothing says so.
//
// So this module does two things: offer the real names an operator should be
// choosing from, and make the lump-invoice case loud instead of silent.
//
// Deliberately NOT done: back-filling which employee sits in which department.
// The workbook that carries that mapping is W1-2026 and its roster has almost
// no overlap with today's — of 49 FabFitFun rows, ZERO matched a current
// employee holding an active assignment. Writing January's departments onto
// September's people would have invented billing facts. That mapping is DT's
// to supply.
//
// PURE — no server imports, so the logic suite can exercise it.

/** Generic fallback for clients with no coded department scheme. */
export const GENERIC_DEPARTMENTS = [
  "Warehouse",
  "Inventory",
  "Receiving",
  "Shipping",
  "Logistics",
  "Hospitality",
] as const;

/**
 * Departments taken verbatim from a client's own invoice workbook, so the
 * string on our invoice matches the string they reconcile against.
 * Keyed on lowercased client name.
 */
export const CLIENT_DEPARTMENTS: Record<string, readonly string[]> = {
  fabfitfun: [
    "502 Warehouse Operations",
    "503 Inventory Control",
    "509 QA Production",
    "510 FC Facility Maintenance",
    "511 FC Engineering",
    "Admin",
  ],
  interconect: ["Warehouse"],
  "interconnect solutions company llc": ["Warehouse"],
};

/** The department a timecard falls into when its assignment carries none. */
export const DEFAULT_DEPARTMENT = "General";

/** Options an operator should pick from for this client. */
export function departmentOptionsFor(clientName: string | null | undefined): readonly string[] {
  const key = (clientName ?? "").trim().toLowerCase();
  return CLIENT_DEPARTMENTS[key] ?? GENERIC_DEPARTMENTS;
}

/** True when this client bills under a coded scheme of its own. */
export function hasCodedDepartments(clientName: string | null | undefined): boolean {
  return Boolean(CLIENT_DEPARTMENTS[(clientName ?? "").trim().toLowerCase()]);
}

export type DepartmentCoverage = {
  /** Assignments with a real department set. */
  covered: number;
  /** Assignments that will collapse into DEFAULT_DEPARTMENT. */
  missing: number;
  /** True when this client wants per-department invoices and cannot get them. */
  degraded: boolean;
  message: string | null;
};

/**
 * How well a client's assignments can support per-department invoicing.
 *
 * `degraded` is the signal worth showing: the client bills by department, and
 * enough assignments lack one that generating now produces a single lump
 * invoice instead. That failure is otherwise invisible — the run succeeds, the
 * invoice looks fine, and it is simply the wrong shape.
 */
export function departmentCoverage(
  clientName: string | null | undefined,
  assignmentDepartments: (string | null | undefined)[],
): DepartmentCoverage {
  let covered = 0;
  let missing = 0;
  for (const d of assignmentDepartments) {
    const v = (d ?? "").trim();
    if (!v || v.toLowerCase() === "unassigned" || v === DEFAULT_DEPARTMENT) missing++;
    else covered++;
  }

  const coded = hasCodedDepartments(clientName);
  const degraded = coded && missing > 0;
  const name = (clientName ?? "this client").trim() || "this client";

  return {
    covered,
    missing,
    degraded,
    message: degraded
      ? `${missing} of ${covered + missing} ${name} assignments have no department, so they will bill as one "${DEFAULT_DEPARTMENT}" invoice instead of one invoice per department. Set each assignment's department to fix this.`
      : null,
  };
}
