import { test, expect } from "@playwright/test";
import {
  departmentOptionsFor,
  hasCodedDepartments,
  departmentCoverage,
  GENERIC_DEPARTMENTS,
  DEFAULT_DEPARTMENT,
} from "../../src/lib/client-departments";

// Rocio, 2026-06-17: "For FabFitFun specifically, invoices must be generated by
// department... each department needs to have its own invoice."
//
// The engine already groups by department. What did not work was the data: the
// picker offered a generic list FabFitFun does not bill under, and 63 of 67 of
// their active assignments had no department at all — so a run produced ONE
// lump invoice and said nothing.

test("FabFitFun gets the coded departments from their own invoice workbook", () => {
  const opts = departmentOptionsFor("FabFitFun");
  expect(opts).toContain("502 Warehouse Operations");
  expect(opts).toContain("503 Inventory Control");
  expect(opts).toContain("509 QA Production");
  expect(opts).toContain("510 FC Facility Maintenance");
  expect(opts).toContain("511 FC Engineering");
});

test("client matching ignores case and surrounding space", () => {
  expect(hasCodedDepartments("  fabfitfun ")).toBe(true);
  expect(hasCodedDepartments("FABFITFUN")).toBe(true);
});

test("a client with no coded scheme falls back to the generic list", () => {
  expect(departmentOptionsFor("Some New Client")).toEqual(GENERIC_DEPARTMENTS);
  expect(departmentOptionsFor(null)).toEqual(GENERIC_DEPARTMENTS);
  expect(hasCodedDepartments("Some New Client")).toBe(false);
});

test("THE PRODUCTION CASE: mostly-blank departments read as degraded", () => {
  // 63 of 67 blank, as measured 2026-09-10.
  const depts = [
    ...Array(63).fill("Unassigned"),
    "Receiving",
    "Warehouse",
    "Warehouse",
    "Warehouse",
  ];
  const cov = departmentCoverage("FabFitFun", depts);
  expect(cov.missing).toBe(63);
  expect(cov.covered).toBe(4);
  expect(cov.degraded).toBe(true);
  expect(cov.message).toMatch(/63 of 67/);
  expect(cov.message).toMatch(/one invoice per department/);
});

test("fully-populated departments are not flagged", () => {
  const cov = departmentCoverage("FabFitFun", ["503 Inventory Control", "502 Warehouse Operations"]);
  expect(cov.degraded).toBe(false);
  expect(cov.message).toBeNull();
});

test("a client that does not bill by department is never flagged", () => {
  const cov = departmentCoverage("Some New Client", [null, null, null]);
  expect(cov.missing).toBe(3);
  expect(cov.degraded).toBe(false);
});

test("blank, whitespace, 'Unassigned' and the default all count as missing", () => {
  const cov = departmentCoverage("FabFitFun", [null, undefined, "", "   ", "Unassigned", DEFAULT_DEPARTMENT]);
  expect(cov.missing).toBe(6);
  expect(cov.covered).toBe(0);
});
