-- Driven Talent — client_contacts seed from DT-LIVE-DATA-2026-06-08.xlsx
-- (Sheet: 'Contact records'). Loaded as part of the 2026-06-09 follow-up to
-- the 2026-06-08 live-data migration. Run AFTER 0020_client_contacts_table.sql.
--
-- Contains 39 unique contacts (deduped by email).
-- Sources: free-form Section 1 (rows 3-69) and tabular Section 2 (rows 73-129).

-- Use insert ... on conflict (lower(email)) do update so this is re-runnable.

insert into client_contacts (
  client_id, full_name, first_name, last_name, department, position,
  phone, email, shift, role_type, notes
) values
  ((select id from clients where slug = 'fabfitfun'), 'Ismael Ramirez', 'Ismael', 'Ramirez', 'Directors', 'Director', null, 'ismael.ramirez@fabfitfun.com', null, 'Director', null),
  ((select id from clients where slug = 'fabfitfun'), 'Nathan Goodrich', 'Nathan', 'Goodrich', 'Directors', 'Director', null, 'nathan.goodrich@fabfitfun.com', null, 'Director', null),
  ((select id from clients where slug = 'fabfitfun'), 'Oscar Delgado', 'Oscar', 'Delgado', 'Directors', 'Director', null, 'oscar.delgado@fabfitfun.com', null, 'Director', null),
  ((select id from clients where slug = 'fabfitfun'), 'Ben Chandler', 'Ben', 'Chandler', 'Executives', 'Executive', null, 'ben.chandler@fabfitfun.com', null, 'Executive', null),
  ((select id from clients where slug = 'fabfitfun'), 'John Gurr', 'John', 'Gurr', 'Executives', 'Executive', null, 'john.gurr@fabfitfun.com', null, 'Executive', null),
  ((select id from clients where slug = 'fabfitfun'), 'Julian VanErlach', 'Julian', 'VanErlach', 'Executives', 'Executive', null, 'julian.vanerlach@fabfitfun.com', null, 'Executive', null),
  ((select id from clients where slug = 'fabfitfun'), 'Paul Mendez', 'Paul', 'Mendez', 'Executives', 'Executive', null, 'paul.mendez@fabfitfun.com', null, 'Executive', null),
  ((select id from clients where slug = 'fabfitfun'), 'Antonio ''Jose'' Diaz', 'Antonio', 'Diaz', 'Facilities', 'Associate Manager', '6262640778', 'jose.diaz@fabfitfun.com', 'AM', 'Associate Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Deric Ball', 'Deric', 'Ball', 'Facilities', 'Supervisor', '6262526764', 'deric.ball@fabfitfun.com', 'PM', 'Supervisor', null),
  ((select id from clients where slug = 'fabfitfun'), 'Brenda Duque', 'Brenda', 'Duque', 'Fulfillment', 'Sr. Manager', '8186750772', 'brenda.duque@fabfitfun.com', 'AM', 'Sr. Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Elisa Penalosa', 'Elisa', 'Penalosa', 'Fulfillment', 'Associate Manager', '3236170459', 'elisa.penalosa@fabfitfun.com', 'AM', 'Associate Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Robert Forsyth', 'Robert', 'Forsyth', 'Fulfillment', 'Associate Manager', '9093688498', 'robert.forsyth@fabfitfun.com', null, 'Associate Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Deysi Saucedo', 'Deysi', 'Saucedo', 'Human Resources', 'Supervisora', null, 'deysi.saucedo@fabfitfun.com', null, 'Supervisor', null),
  ((select id from clients where slug = 'fabfitfun'), 'Zobeida Valdez', 'Zobeida', 'Valdez', 'Human Resources', null, null, 'zobeida.valdez-contractor@fabfitfun.com', null, null, null),
  ((select id from clients where slug = 'fabfitfun'), 'HR BP (shared inbox)', null, null, 'Human Resources', 'HR BP', null, 'hr.fc@fabfitfun.com', null, 'HR', 'Shared HR inbox; no individual contact'),
  ((select id from clients where slug = 'fabfitfun'), 'Brandon Martinez', 'Brandon', 'Martinez', 'Inventory Control', 'Inventory Control', '6268980768', 'brandon.martinez@fabfitfun.com', null, 'Inventory', null),
  ((select id from clients where slug = 'fabfitfun'), 'Joseph Ortega', 'Joseph', 'Ortega', 'Inventory Control', 'Operations Coordinator', null, 'joseph.ortega@fabfitfun.com', null, 'Coordinator', null),
  ((select id from clients where slug = 'fabfitfun'), 'Lamar Tisdom', 'Lamar', 'Tisdom', 'Inventory Control', 'Inventory Manager', '9092603065', 'lamar.tisdom@fabfitfun.com', null, 'Inventory', null),
  ((select id from clients where slug = 'fabfitfun'), 'Stephanie Almanza', 'Stephanie', 'Almanza', 'Inventory Control', 'Inventory Control', '6262368511', 'stephanie.almanza@fabfitfun.com', null, 'Inventory', null),
  ((select id from clients where slug = 'fabfitfun'), 'Mark Wacker', 'Mark', 'Wacker', 'Maintenance', 'Associate Manager', '9092151486', 'mark.wacker@fabfitfun.com', null, 'Associate Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Armando Perez', 'Armando', 'Perez', 'Production & Shipping', 'Supervisor', '9095241029', 'armando.perez@fabfitfun.com', null, 'Supervisor', null),
  ((select id from clients where slug = 'fabfitfun'), 'Hector Cornejo', 'Hector', 'Cornejo', 'Production & Shipping', 'Manager', '6263922253', 'hector.cornejo@fabfitfun.com', null, 'Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Krystal Ford', 'Krystal', 'Ford', 'Production & Shipping', 'Sr. Manager', '5623280062', 'krystal.ford@fabfitfun.com', null, 'Sr. Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Lydia Garcia', 'Lydia', 'Garcia', 'Production & Shipping', 'Supervisor', '2133187913', 'lydia.garcia@fabfitfun.com', null, 'Supervisor', null),
  ((select id from clients where slug = 'fabfitfun'), 'Omar Marquez', 'Omar', 'Marquez', 'Production & Shipping', 'Associate Manager', '9093580562', 'omar.marquez@fabfitfun.com', null, 'Associate Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Susan Sic', 'Susan', 'Sic', 'Production & Shipping', 'Supervisor', '3234741902', 'susan.sic@fabfitfun.com', null, 'Supervisor', null),
  ((select id from clients where slug = 'fabfitfun'), 'Tania Cardenas', 'Tania', 'Cardenas', 'Production & Shipping', 'Supervisor', '6269566308', 'tania.cardenas@fabfitfun.com', null, 'Supervisor', null),
  ((select id from clients where slug = 'fabfitfun'), 'Bilvia Garcia', 'Bilvia', 'Garcia', 'Quality', 'Supervisor', '5626469878', 'bilvia@fabfitfun.com', 'AM', 'Supervisor', null),
  ((select id from clients where slug = 'fabfitfun'), 'Brenda Navarro', 'Brenda', 'Navarro', 'Quality', 'Supervisor', '9095215942', 'brenda.navarro@fabfitfun.com', null, 'Supervisor', null),
  ((select id from clients where slug = 'fabfitfun'), 'Veronica Alvarran', 'Veronica', 'Alvarran', 'Quality', 'Associate Manager', '3237815544', 'veronica.alvarran@fabfitfun.com', null, 'Associate Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Carlos Cisneros', 'Carlos', 'Cisneros', 'Receiving & Whse', 'Manager', '9515207917', 'carlos.cisneros@fabfitfun.com', 'AM', 'Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Edgar Lopez', 'Edgar', 'Lopez', 'Receiving & Whse', 'Supervisor', '6266729849', 'edgar.lopez@fabfitfun.com', 'PM', 'Supervisor', null),
  ((select id from clients where slug = 'fabfitfun'), 'Jimmy Martinez', 'Jimmy', 'Martinez', 'Receiving & Whse', 'Lead AM', '3233580809', 'jimmy.martinez@fabfitfun.com', null, 'Lead', null),
  ((select id from clients where slug = 'fabfitfun'), 'Mario Garcia', 'Mario', 'Garcia', 'Receiving & Whse', 'Manager', '5625777748', 'mario.garcia@fabfitfun.com', 'PM', 'Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Robinson Lopez', 'Robinson', 'Lopez', 'Receiving & Whse', 'Supervisor', '6263470062', 'robinson.lopez@fabfitfun.com', 'AM', 'Supervisor', null),
  ((select id from clients where slug = 'fabfitfun'), 'Bill Dietzen', 'Bill', 'Dietzen', 'Safety/Security', 'Manager, Security', '7144148222', 'bill.dietzen@fabfitfun.com', null, 'Manager', null),
  ((select id from clients where slug = 'fabfitfun'), 'Jose Alvarado', 'Jose', 'Alvarado', 'Safety/Security', 'Supervisor', null, 'jose.alvarado@fabfitfun.com', null, 'Supervisor', null),
  ((select id from clients where slug = 'fabfitfun'), 'Sean Liske', 'Sean', 'Liske', 'Safety/Security', 'Manager, Safety', '9092622987', 'sean.liske@fabfitfun.com', null, 'Manager', null),
  ((select id from clients where slug = 'isc'), 'Susie', 'Susie', null, null, 'HR assistant', null, 'sgrijalva@interconnectsolutions.com', null, 'HR', null)
on conflict ((lower(email))) where email is not null do update set
  client_id    = excluded.client_id,
  full_name    = excluded.full_name,
  first_name   = excluded.first_name,
  last_name    = excluded.last_name,
  department   = excluded.department,
  position     = excluded.position,
  phone        = excluded.phone,
  shift        = excluded.shift,
  role_type    = excluded.role_type,
  notes        = excluded.notes,
  updated_at   = now();

-- Stash a parse-time backup of the raw source rows in migration_unresolved
-- so the structured payload survives independent of the contacts table.
-- This is a no-op when re-run because of the source_sheet+source_row+payload identity.

insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 121, 'backup-of-loaded-contact', '{"full_name": "Ismael Ramirez", "email": "ismael.ramirez@fabfitfun.com", "department": "Directors", "position": "Director", "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": "Director", "sources": ["2b-dir"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 103, 'backup-of-loaded-contact', '{"full_name": "Nathan Goodrich", "email": "nathan.goodrich@fabfitfun.com", "department": "Directors", "position": "Director", "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": "Director", "sources": ["2b-dir"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 50, 'backup-of-loaded-contact', '{"full_name": "Oscar Delgado", "email": "oscar.delgado@fabfitfun.com", "department": "Directors", "position": "Director", "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": "Director", "sources": ["1", "2b-dir", "2b-dir"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 103, 'backup-of-loaded-contact', '{"full_name": "Ben Chandler", "email": "ben.chandler@fabfitfun.com", "department": "Executives", "position": "Executive", "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": "Executive", "sources": ["2b-exec", "2b-dir"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 103, 'backup-of-loaded-contact', '{"full_name": "John Gurr", "email": "john.gurr@fabfitfun.com", "department": "Executives", "position": "Executive", "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": "Executive", "sources": ["2b-exec"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 103, 'backup-of-loaded-contact', '{"full_name": "Julian VanErlach", "email": "julian.vanerlach@fabfitfun.com", "department": "Executives", "position": "Executive", "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": "Executive", "sources": ["2b-exec"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 103, 'backup-of-loaded-contact', '{"full_name": "Paul Mendez", "email": "paul.mendez@fabfitfun.com", "department": "Executives", "position": "Executive", "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": "Executive", "sources": ["2b-exec"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 58, 'backup-of-loaded-contact', '{"full_name": "Antonio ''Jose'' Diaz", "email": "jose.diaz@fabfitfun.com", "department": "Facilities", "position": "Associate Manager", "phone": "6262640778", "shift": "AM", "client_slug": "fabfitfun", "role_type": "Associate Manager", "sources": ["1", "2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 58, 'backup-of-loaded-contact', '{"full_name": "Deric Ball", "email": "deric.ball@fabfitfun.com", "department": "Facilities", "position": "Supervisor", "phone": "6262526764", "shift": "PM", "client_slug": "fabfitfun", "role_type": "Supervisor", "sources": ["1", "2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 88, 'backup-of-loaded-contact', '{"full_name": "Brenda Duque", "email": "brenda.duque@fabfitfun.com", "department": "Fulfillment", "position": "Sr. Manager", "phone": "8186750772", "shift": "AM", "client_slug": "fabfitfun", "role_type": "Sr. Manager", "sources": ["2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 89, 'backup-of-loaded-contact', '{"full_name": "Elisa Penalosa", "email": "elisa.penalosa@fabfitfun.com", "department": "Fulfillment", "position": "Associate Manager", "phone": "3236170459", "shift": "AM", "client_slug": "fabfitfun", "role_type": "Associate Manager", "sources": ["2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 90, 'backup-of-loaded-contact', '{"full_name": "Robert Forsyth", "email": "robert.forsyth@fabfitfun.com", "department": "Fulfillment", "position": "Associate Manager", "phone": "9093688498", "shift": null, "client_slug": "fabfitfun", "role_type": "Associate Manager", "sources": ["2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 50, 'backup-of-loaded-contact', '{"full_name": "Deysi Saucedo", "email": "deysi.saucedo@fabfitfun.com", "department": "Human Resources", "position": "Supervisora", "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": "Supervisor", "sources": ["1", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 129, 'backup-of-loaded-contact', '{"full_name": "Zobeida Valdez", "email": "zobeida.valdez-contractor@fabfitfun.com", "department": "Human Resources", "position": null, "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": null, "sources": ["2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 125, 'backup-of-loaded-contact', '{"full_name": "HR BP (shared inbox)", "email": "hr.fc@fabfitfun.com", "department": "Human Resources", "position": "HR BP", "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": "HR", "sources": ["2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 3, 'backup-of-loaded-contact', '{"full_name": "Brandon Martinez", "email": "brandon.martinez@fabfitfun.com", "department": "Inventory Control", "position": "Inventory Control", "phone": "6268980768", "shift": null, "client_slug": "fabfitfun", "role_type": "Inventory", "sources": ["1", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 3, 'backup-of-loaded-contact', '{"full_name": "Joseph Ortega", "email": "joseph.ortega@fabfitfun.com", "department": "Inventory Control", "position": "Operations Coordinator", "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": "Coordinator", "sources": ["1", "2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 78, 'backup-of-loaded-contact', '{"full_name": "Lamar Tisdom", "email": "lamar.tisdom@fabfitfun.com", "department": "Inventory Control", "position": "Inventory Manager", "phone": "9092603065", "shift": null, "client_slug": "fabfitfun", "role_type": "Inventory", "sources": ["2a"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 3, 'backup-of-loaded-contact', '{"full_name": "Stephanie Almanza", "email": "stephanie.almanza@fabfitfun.com", "department": "Inventory Control", "position": "Inventory Control", "phone": "6262368511", "shift": null, "client_slug": "fabfitfun", "role_type": "Inventory", "sources": ["1", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 54, 'backup-of-loaded-contact', '{"full_name": "Mark Wacker", "email": "mark.wacker@fabfitfun.com", "department": "Maintenance", "position": "Associate Manager", "phone": "9092151486", "shift": null, "client_slug": "fabfitfun", "role_type": "Associate Manager", "sources": ["1", "2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 87, 'backup-of-loaded-contact', '{"full_name": "Armando Perez", "email": "armando.perez@fabfitfun.com", "department": "Production & Shipping", "position": "Supervisor", "phone": "9095241029", "shift": null, "client_slug": "fabfitfun", "role_type": "Supervisor", "sources": ["2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 82, 'backup-of-loaded-contact', '{"full_name": "Hector Cornejo", "email": "hector.cornejo@fabfitfun.com", "department": "Production & Shipping", "position": "Manager", "phone": "6263922253", "shift": null, "client_slug": "fabfitfun", "role_type": "Manager", "sources": ["2a"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 81, 'backup-of-loaded-contact', '{"full_name": "Krystal Ford", "email": "krystal.ford@fabfitfun.com", "department": "Production & Shipping", "position": "Sr. Manager", "phone": "5623280062", "shift": null, "client_slug": "fabfitfun", "role_type": "Sr. Manager", "sources": ["2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 83, 'backup-of-loaded-contact', '{"full_name": "Lydia Garcia", "email": "lydia.garcia@fabfitfun.com", "department": "Production & Shipping", "position": "Supervisor", "phone": "2133187913", "shift": null, "client_slug": "fabfitfun", "role_type": "Supervisor", "sources": ["2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 84, 'backup-of-loaded-contact', '{"full_name": "Omar Marquez", "email": "omar.marquez@fabfitfun.com", "department": "Production & Shipping", "position": "Associate Manager", "phone": "9093580562", "shift": null, "client_slug": "fabfitfun", "role_type": "Associate Manager", "sources": ["2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 85, 'backup-of-loaded-contact', '{"full_name": "Susan Sic", "email": "susan.sic@fabfitfun.com", "department": "Production & Shipping", "position": "Supervisor", "phone": "3234741902", "shift": null, "client_slug": "fabfitfun", "role_type": "Supervisor", "sources": ["2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 86, 'backup-of-loaded-contact', '{"full_name": "Tania Cardenas", "email": "tania.cardenas@fabfitfun.com", "department": "Production & Shipping", "position": "Supervisor", "phone": "6269566308", "shift": null, "client_slug": "fabfitfun", "role_type": "Supervisor", "sources": ["2a"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 94, 'backup-of-loaded-contact', '{"full_name": "Bilvia Garcia", "email": "bilvia@fabfitfun.com", "department": "Quality", "position": "Supervisor", "phone": "5626469878", "shift": "AM", "client_slug": "fabfitfun", "role_type": "Supervisor", "sources": ["2a"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 50, 'backup-of-loaded-contact', '{"full_name": "Brenda Navarro", "email": "brenda.navarro@fabfitfun.com", "department": "Quality", "position": "Supervisor", "phone": "9095215942", "shift": null, "client_slug": "fabfitfun", "role_type": "Supervisor", "sources": ["1", "2a", "2b", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 93, 'backup-of-loaded-contact', '{"full_name": "Veronica Alvarran", "email": "veronica.alvarran@fabfitfun.com", "department": "Quality", "position": "Associate Manager", "phone": "3237815544", "shift": null, "client_slug": "fabfitfun", "role_type": "Associate Manager", "sources": ["2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 74, 'backup-of-loaded-contact', '{"full_name": "Carlos Cisneros", "email": "carlos.cisneros@fabfitfun.com", "department": "Receiving & Whse", "position": "Manager", "phone": "9515207917", "shift": "AM", "client_slug": "fabfitfun", "role_type": "Manager", "sources": ["2a"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 10, 'backup-of-loaded-contact', '{"full_name": "Edgar Lopez", "email": "edgar.lopez@fabfitfun.com", "department": "Receiving & Whse", "position": "Supervisor", "phone": "6266729849", "shift": "PM", "client_slug": "fabfitfun", "role_type": "Supervisor", "sources": ["1", "2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 10, 'backup-of-loaded-contact', '{"full_name": "Jimmy Martinez", "email": "jimmy.martinez@fabfitfun.com", "department": "Receiving & Whse", "position": "Lead AM", "phone": "3233580809", "shift": null, "client_slug": "fabfitfun", "role_type": "Lead", "sources": ["1", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 10, 'backup-of-loaded-contact', '{"full_name": "Mario Garcia", "email": "mario.garcia@fabfitfun.com", "department": "Receiving & Whse", "position": "Manager", "phone": "5625777748", "shift": "PM", "client_slug": "fabfitfun", "role_type": "Manager", "sources": ["1", "2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 10, 'backup-of-loaded-contact', '{"full_name": "Robinson Lopez", "email": "robinson.lopez@fabfitfun.com", "department": "Receiving & Whse", "position": "Supervisor", "phone": "6263470062", "shift": "AM", "client_slug": "fabfitfun", "role_type": "Supervisor", "sources": ["1", "2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 99, 'backup-of-loaded-contact', '{"full_name": "Bill Dietzen", "email": "bill.dietzen@fabfitfun.com", "department": "Safety/Security", "position": "Manager, Security", "phone": "7144148222", "shift": null, "client_slug": "fabfitfun", "role_type": "Manager", "sources": ["2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 100, 'backup-of-loaded-contact', '{"full_name": "Jose Alvarado", "email": "jose.alvarado@fabfitfun.com", "department": "Safety/Security", "position": "Supervisor", "phone": null, "shift": null, "client_slug": "fabfitfun", "role_type": "Supervisor", "sources": ["2a", "2b"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 98, 'backup-of-loaded-contact', '{"full_name": "Sean Liske", "email": "sean.liske@fabfitfun.com", "department": "Safety/Security", "position": "Manager, Safety", "phone": "9092622987", "shift": null, "client_slug": "fabfitfun", "role_type": "Manager", "sources": ["2a"]}'::jsonb);
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 69, 'backup-of-loaded-contact', '{"full_name": "Susie", "email": "sgrijalva@interconnectsolutions.com", "department": null, "position": "HR assistant", "phone": null, "shift": null, "client_slug": "isc", "role_type": "HR", "sources": ["1"]}'::jsonb);

-- True unresolved (could not parse cleanly):
insert into migration_unresolved (source_sheet, source_row, reason, payload) values ('Contact records', 126, 'section 2b row with no email', '{"source_row": 126, "raw": "[None, None, None, None, ''HR Director'', None, None]", "reason": "section 2b row with no email", "department": "Human Resources"}'::jsonb);
